version: '2.4'

services:
  bundler:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./bundler:/app
      - ../contracts/lib/account-abstraction:/app/submodules/account-abstraction
      - /dev/null:/app/submodules/account-abstraction/.git
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BUNDLER_PORT}"]
      interval: 5s
      timeout: 1s
      retries: 100
      start_period: 3s
    env_file:
      - ../.env
    working_dir: /app
    depends_on:
      forge-deployer:
        condition: service_completed_successfully
    ports:
      - "${BUNDLER_PORT}:${BUNDLER_PORT}"
    cpus: 8
    mem_limit: 32G
    mem_reservation: 32G
    mem_swappiness: 100
    memswap_limit: 32G
    command: ./run.sh
  
  paymaster:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./paymaster:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PAYMASTER_PORT}/health"]
      interval: 5s
      timeout: 1s
      retries: 100
      start_period: 3s
    restart: always
    depends_on:
      forge-deployer:
        condition: service_completed_successfully
    env_file:
      - ../.env
    working_dir: /app
    ports:
      - "${PAYMASTER_PORT}:${PAYMASTER_PORT}"
    command: ./run.sh
  
  naming-service:
    image: "node:20-buster-slim"
    volumes:
      - ./naming-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${NAMING_SERVICE_PORT}/health"]
      interval: 5s
      timeout: 1s
      retries: 100
      start_period: 3s
    restart: always
    env_file:
      - ../.env
    working_dir: /app
    depends_on:
      naming-service-db:
        condition: service_healthy
      forge-deployer:
        condition: service_completed_successfully
    ports:
      - "${NAMING_SERVICE_PORT}:${NAMING_SERVICE_PORT}"
      - 5555:5555
    command: ./run.sh

  naming-service-db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    env_file:
      - ../.env
    volumes:
      - ./naming-service-db/data:/var/lib/postgresql/data

  ledger-live:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./ledger-live:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT}"]
      interval: 5s
      timeout: 1s
      retries: 100
      start_period: 3s
    restart: always
    env_file:
      - ../.env
    environment:
      - VITE_NETWORK=${RPC}
      - VITE_BUNDLER=${BUNDLER}
      - VITE_PAYMASTER=${PAYMASTER}
      - VITE_NAMING_SERVICE=${NAMING_SERVICE}
      - VITE_MOCK_ANVIL_EXPLORER=${MOCK_ANVIL_EXPLORER}
    working_dir: /app
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: ./run.sh

  dapp:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./dapp:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DAPP_PORT}"]
      interval: 5s
      timeout: 1s
      retries: 100
      start_period: 3s
    restart: always
    env_file:
      - ../.env
    environment:
      - VITE_NETWORK=${RPC}
    working_dir: /app
    ports:
      - "${DAPP_PORT}:${DAPP_PORT}"
    command: ./run.sh

  mock-anvil-explorer:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./mock-anvil-explorer:/app
    restart: always
    env_file:
      - ../.env
    working_dir: /app
    ports:
      - "${MOCK_ANVIL_EXPLORER_PORT}:${MOCK_ANVIL_EXPLORER_PORT}"
    command: ./run.sh

  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    platform: linux/amd64
    env_file:
      - ../.env
    ports:
      - "8545:8545"
    command: -c "anvil --steps-tracing --block-time 5 --host 0.0.0.0"