version: '2.4'

services:
  bundler:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./bundler:/app
    restart: always
    env_file:
      - .env
    working_dir: /app
    ports:
      - "${BUNDLER_PORT}:${BUNDLER_PORT}"
    cpus: 8
    mem_limit: 32G
    mem_reservation: 32G
    mem_swappiness: 100
    memswap_limit: 32G
    command: ./run.sh
  
  paymaster:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./paymaster:/app
    restart: always
    env_file:
      - .env
    working_dir: /app
    ports:
      - "${PAYMASTER_PORT}:${PAYMASTER_PORT}"
    command: ./run.sh
  
  naming-service:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./naming-service:/app
    restart: always
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - naming-service-db
    ports:
      - "${NAMING_SERVICE_PORT}:${NAMING_SERVICE_PORT}"
      - 5555:5555
    command: ./run.sh

  naming-service-db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - ./naming-service-db/data:/var/lib/postgresql/data

  ledger-live:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./ledger-live:/app
    restart: always
    env_file:
      - .env
    environment:
      - VITE_NETWORK=${RPC}
      - VITE_BUNDLER=${BUNDLER}
      - VITE_PAYMASTER=${PAYMASTER}
      - VITE_NAMING_SERVICE=${NAMING_SERVICE}
      - VITE_ENTRYPOINT=${ENTRYPOINT_CONTRACT}
      - VITE_WALLETFACTORY_CONTRACT=${FACTORY_CONTRACT}
    working_dir: /app
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: ./run.sh

  dapp:
    image: "node:20-buster-slim"
    user: "root"
    volumes:
      - ./dapp:/app
    restart: always
    env_file:
      - .env
    environment:
      - VITE_NETWORK=${RPC}
    working_dir: /app
    ports:
      - "${DAPP_PORT}:${DAPP_PORT}"
    command: ./run.sh